### ISSUE TITLE
permission denied 

### ISSUE THREAD

**Issue by izk8** [dnzzcn/cuDNNv#1]
Ran the program and got:

```
rm: cannot remove '/usr/include/cudnn.h': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so.6': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so.7': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn_static.a': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a': Permission denied
rm: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a': Permission denied
rm: cannot remove '/usr/local/cuda-8.0/lib64/libcudnn.so': Permission denied
rm: cannot remove '/usr/local/cuda-8.0/lib64/libcudnn.so.5': Permission denied
rm: cannot remove '/usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5': Permission denied
rm: cannot remove '/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10': Permission denied
rm: cannot remove '/usr/local/cuda-8.0/lib64/libcudnn_static.a': Permission denied
cp: cannot create regular file '/usr/include/cudnn.h': Permission denied
cp: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so': Permission denied
cp: cannot remove '/usr/lib/x86_64-linux-gnu/libcudnn.so.6': Permission denied
cp: cannot create regular file '/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21': Permission denied
cp: cannot create regular file '/usr/lib/x86_64-linux-gnu/libcudnn_static.a': Permission denied
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn.so': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn.so.6': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn.so.7': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn_static.a': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a': Operation not permitted
chmod: changing permissions of '/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a': Operation not permitted

```

**Comment by izk8** [comment]
Going to try to erase the package and reinstall since I had an old one and pulled the latest but who knows. Obviously something to do with the permissions on those files (sudo needed?).

**Comment by dnzzcn** [comment]
cuDNNv tries to delete files related to pre-installed cuDNN versions, and it throws an error if it can't achieve deleting due to permission restrictions. Using sudo should solve the problem. It is safe to use sudo for this purpose, since the only thing cuDNNv does is handling transfering of cuDNN related files.

**Comment by estathop** [comment]
sudo does the trick
